#version: "3.8"
services:
  app:
    image: 366d986cdb26
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
    - /home/diaznjuan/g9-ia-curso/agente_ia_g9:/app
    working_dir: /app
    environment:
      - HF_HOME=/app/huggingface # Establece la carpeta de Hugging Face
      - CUDA_VISIBLE_DEVICES=0
    stdin_open: true
    tty: true
    entrypoint: >
      sh -c "/bin/bash"